#ifndef POSTCOMMANDTYPE_H
#define POSTCOMMANDTYPE_H

enum PostCommandType {
    NULL_COMMAND,
    ADD_MARK,
    DELETE_MARK,
    LEFT_STEP,
    RIGHT_STEP,
    CHECK_MARK,
    STOP
};

#endif // POSTCOMMANDTYPE_H
